# Site settings
<<<<<<< HEAD
title: Test Engineering Notes
header-img: img/home-bg.jpg
email: al8x.romanov@gmail.com
copyright_name: Oleksandr Romanov
description: "Notes and experiences in test engineering, automation and distributed systems"
=======
title: Software Engineering Notes
header-img: img/home-bg.jpg
email: al8x.romanov@gmail.com
copyright_name: Oleksandr Romanov
description: "Notes and experiences in software engineering, automation and quality"
>>>>>>> 0e37d7a8c3e10ef722e1062ad12e5b639847e9f9
name: "Oleksandr Romanov's blog"
baseurl: ""
url: "https://alexromanov.github.io"
twitter_username: al8xr
github_username:  alexromanov
facebook_username:  al8x.romanov
email_username:  al8x.romanov@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-81345534-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]
